-- local Players = game:GetService("Players")
-- local Player = Players.LocalPlayer

-- local Character = Player.Character

-- local Seat = Character.Humanoid.SeatPart

-- print(Seat.AssemblyLinearVelocity.Magnitude)

-- Generated by Hydroxide's Upvalue Scanner: https://github.com/Upbolt/Hydroxide

local aux = loadstring(game:HttpGetAsync("https://raw.githubusercontent.com/Upbolt/Hydroxide/revision/ohaux.lua"))()


local scriptPath = game:GetService("Players").LocalPlayer.Backpack.Control
local closureName = "SetControlled"
local upvalueIndex = 5
local closureConstants = {
	[1] = "Name",
	[2] = "Bomber",
	[3] = "TargetFilter",
	[4] = "MainBody",
	[5] = "WaitForChild",
	[6] = "BodyGyro"
}

local closure = aux.searchClosure(scriptPath, closureName, upvalueIndex, closureConstants)
local value = 250

-- DO NOT RELY ON THIS FEATURE TO PRODUCE 100% FUNCTIONAL SCRIPTS
debug.setupvalue(closure, upvalueIndex, value)
